
services:
  backend:
    network_mode: "host"
    build: ./backend
    image: my_web_app_backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:rey0608@${HOST_IP}:5432/my_test_db
    ports:
      - "8000:8000"

